// <auto-generated />
using System;
using Gunluk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazı1",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1389),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1380)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazı2",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1410),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1409)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazı3",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1411),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1411)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazı4",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1413),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1412)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazı5",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1414),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1414)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazı6",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1416),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1416)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazı7",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1417),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1417)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazı8",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1419),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1418)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazı9",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1420),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1419)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazı10",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1421),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1421)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazı11",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1422),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1422)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazı12",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1423),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1423)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazı13",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1425),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1424)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazı14",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1426),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1426)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazı15",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1427),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1427)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazı16",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1428),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1428)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazı17",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1429),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1429)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazı18",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1430),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1430)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazı19",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1432),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1431)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazı20",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1433),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1432)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazı21",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1434),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1433)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazı22",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1435),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1434)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazı23",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1436),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1435)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazı24",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1437),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1436)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazı25",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1438),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1438)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazı26",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1439),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1439)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazı27",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1440),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1440)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazı28",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1441),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1441)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazı29",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1442),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1442)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazı30",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1443),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1443)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazı31",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1445),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1444)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazı32",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1446),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1445)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazı33",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1447),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1446)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazı34",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1448),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1447)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazı35",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1449),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1448)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazı36",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1473),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1471)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazı37",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1474),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1474)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazı38",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1475),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1475)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazı39",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1476),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1476)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazı40",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1478),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1477)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazı41",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1479),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1478)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazı42",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1480),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1479)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazı43",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1481),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1481)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazı44",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1482),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1482)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazı45",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1483),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1483)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazı46",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1484),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1484)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazı47",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1485),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1485)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazı48",
                            DegistirilmeTarihi = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1486),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 14, 22, 867, DateTimeKind.Local).AddTicks(1486)
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Karışık"
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.HasOne("Gunluk.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
